/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package omar.cucumber.ingest.test

import omar.cucumber.ingest.test.TomcatStart
import omar.cucumber.ingest.test.CucumberTest

class App {
    public static void main(String[] args) throws Throwable {

        if (System.getenv("runEnv") == "local")
        {
            CucumberTest ingest = new CucumberTest()
            ingest.startTest()
        } else {
            TomcatStart tomcat = new TomcatStart()
            tomcat.startServer()
        }
    }
}
